/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/facecap.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/facecap.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" scale={10}>
          <group name="grp_scale" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="grp_transform" rotation={[-0.022, -0.033, -0.008]}>
              <group name="grp_eyeLeft" position={[-3.289, 2.382, -2.612]} rotation={[0.168, -0.003, -0.015]}>
                <group name="eyeLeft">
                  <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.lambert5} position={[-10.903, -18.028, -18.131]} scale={0.002} />
                </group>
              </group>
              <group name="grp_eyeRight" position={[3.289, 2.382, -2.612]} rotation={[0.167, -0.012, -0.07]}>
                <group name="eyeRight">
                  <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={materials.lambert5} position={[-10.903, -18.028, -18.131]} scale={0.002} />
                </group>
              </group>
              <group name="head">
                <mesh name="mesh_2" geometry={nodes.mesh_2.geometry} material={materials.lambert5} morphTargetDictionary={nodes.mesh_2.morphTargetDictionary} morphTargetInfluences={nodes.mesh_2.morphTargetInfluences} position={[-10.903, -18.028, -18.131]} scale={0.002} />
              </group>
              <group name="teeth">
                <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={materials.lambert5} position={[-10.903, -18.028, -18.131]} scale={0.002} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/facecap.glb')
